---
- name: AWS Stack Builder
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: Create AWS Stack
      cloudformation:
        stack_name: "{{ stack_prefix }}"
        region: "ap-southeast-2"
        state: present
        disable_rollback: true
        template: "../templates/code.yaml"
        template_parameters:
          ComputeKeyPairNameParameter: "{{ key_name }}"
